---
title: "bulk-org figures (AB)"
author: "Raphael Kubler"
date: "01/16/2024"
output:
  rmarkdown::html_document:
   theme: united
   highlight: tango
   code_folding: hide
   toc: true
   toc_float: true
   df_print: paged
   smooth_scroll: true
   number_sections: false
   self_contained: true 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

load('~/Documents/R projects/bulk-org/01152024_AB figures analysis.RData')


library(tibble)
library(matrixStats)
library(factoextra)
library(broom)
library(ggpubr)
library(tidyr)
library(dplyr)
library(plyr)
library(ggeasy)
library(ggrepel)
library(gridExtra)
library(ComplexHeatmap)
library(DESeq2)
library(dplyr)
library(plyr)
library(clusterProfiler)
library(tidyr)
library(biomaRt)
library(variancePartition)
library(ggrastr)
library(kableExtra)
```

# CO vs COiMG in control samples

## PCA plots
```{r pca, echo=TRUE, fig.align = "center", message = FALSE, warning=FALSE, eval=TRUE}
#pca plots
PCAplot(pca.ctr, "Line", Shape = "COiMg", PoV.df=PoV.ctr, pc.1 = 1, pc.2 = 2) #M30 & M33 are outleirs, let's remove them for now
PCAplot(pca.ctr, "condition", Shape = "Line", PoV.df=PoV.ctr, pc.1 = 1, pc.2 = 2) #M30 & M33 are outleirs, let's remove them for now
PCAplot(pca.ctr, "COiMg", Shape = "Line", PoV.df=PoV.ctr, pc.1 = 1, pc.2 = 2) #M30 & M33 are outleirs, let's remove them for now

```

## Volcano plot

```{r volcano.new_coimg, echo=TRUE, fig.height = 4, fig.width = 5, fig.align = "center", message = FALSE, warning=FALSE, eval=TRUE}

volcano_plot(data.frame(new_coimg), title = 'CO vs COiMg',
             annotate_by=top40.ctr, ymax1 = 30, ymax2 = 31, xmax1 = -5, xmax2 = 8)

```

## Boxplot genes of interest

```{r dea, echo=TRUE, fig.height = 4, fig.width = 5, fig.align = "center", message = FALSE, warning=FALSE, eval=TRUE}
ggplot(expression_data_long,aes(x = Gene, y = Expression, fill = COiMG)) +
  geom_boxplot(position = position_dodge(width = 0.8), width = 0.7)  +
  theme_minimal()
```


## Patir microglia genes heatmap

```{r heatmap.top50, echo=TRUE, fig.height = 4, fig.width = 10, fig.align = "center", message = FALSE, warning=FALSE, eval=TRUE}
ComplexHeatmap::Heatmap(hm_counts.ctr,
                        cluster_rows = T,
                        cluster_columns = T,
                        show_row_dend = T,
                        show_column_dend = T,
                        show_row_names = F,
                        show_column_names = F,
                        left_annotation = ra.ctr,
                        bottom_annotation = HeatmapAnnotation(
                          text = anno_text(colnames(hm_counts.ctr), rot = 300, just = "left",gp=gpar(fontsize=8))),
                        col = colorRampPalette(rev(RColorBrewer::brewer.pal(9,"RdBu")))(10),
                        name = "Z-score expression")
```
## Enrichment heatmap (gene sets of interest)
```{r coimg.table, echo=TRUE, fig.height = 6, fig.width = 5, message = FALSE, warning=FALSE, eval=TRUE}
ComplexHeatmap::Heatmap(DEG.enrich_coimg,
                        cluster_rows = F,
                        cluster_columns = F,
                        show_row_dend = F,
                        show_column_dend = F,
                        show_row_names = T,
                        col = colorRampPalette(RColorBrewer::brewer.pal(9,"Blues"))(30),
                        name = "log2(q)",
)


```

## GO enrichment

```{r GO, echo=TRUE, fig.height = 10, fig.width = 7, fig.align = "center", message = FALSE, warning=FALSE, eval=TRUE}
dotplot(new_coimg.upregGO, split="ONTOLOGY", showCategory=10) + facet_grid(ONTOLOGY~., scale="free")
dotplot(new_coimg.downregGO, split="ONTOLOGY", showCategory=10) + facet_grid(ONTOLOGY~., scale="free")

```

## IFNy CO vs COiMG

```{r enrichment, echo=TRUE, fig.height = 6, fig.width = 6, fig.align = "center", message = FALSE, warning=FALSE, eval=TRUE}
ctr_CO <- batch.rem3_mod1[,colnames(batch.rem3_mod1) %in% rownames(meta[meta$COiMg %in% "no" & meta$condition %in% "IFNg",])]
ctr_COiMG <- batch.rem3_mod1[,colnames(batch.rem3_mod1) %in% rownames(meta[meta$COiMg %in% "yes" & meta$condition %in% "IFNg",])]
cor(ctr_CO,ctr_COiMG)

df1 <- data.frame('CO'=rowMeans(ctr_CO))
df2 <- data.frame('COiMG'=rowMeans(ctr_COiMG))

df.plot <- cbind(df1,df2)

quantile(as.matrix(df1-df2))
rownames(df.plot)[df1-df2 >= 1 | df1-df2 <= -4]

Gene <- ifelse(rownames(df.plot) %in% rownames(df.plot)[df1-df2 >= 1 | df1-df2 <= -4], rownames(df.plot), "")

ggplot(df.plot, aes(x=CO,y=COiMG))+
  geom_point() +
  labs(title = "Expression overlap CO vs COiMG under IFNy stimulation",
       x = "Standardized CO counts",
       y = "Standardized COiMG counts") +
  geom_smooth(method=lm,  linetype="dashed",
             color="darkred", fill="blue", se=TRUE) +
  geom_point(shape=18, color="grey")+
  stat_cor(method = "pearson", label.x = 0, label.y = 20)+
  geom_text_repel(data = df.plot, aes(x = CO, y = COiMG, label = Gene), vjust = 3, size = 3) +
  theme_minimal()

```

# Stimulation (IFNy) samples

## PCA plots
```{r pca.2, echo=TRUE, fig.align = "center", message = FALSE, warning=FALSE, eval=TRUE}
PCAplot(pca.ifny, "condition", Shape = "Line", PoV.df=PoV.ifny, pc.1 = 1, pc.2 = 2) #M30 & M33 are outleirs, let's remove them for now

```

## Volcano plot

```{r volcano.stim, echo=TRUE,  fig.height = 5, fig.width = 5, fig.align = "center", message = FALSE, warning=FALSE, eval=TRUE}
new_IFNy$symbol <- rownames(new_IFNy)
top30.new_IFNy <- c(rownames(new_IFNy[order(new_IFNy$log2FoldChange),][new_IFNy[order(new_IFNy$log2FoldChange),]$padj < 0.05,][1:15,]),
                    rownames(new_IFNy[order(new_IFNy$log2FoldChange, decreasing = T),][new_IFNy[order(new_IFNy$log2FoldChange, decreasing = T),]$padj < 0.05,][1:15,]))

volcano_plot(data.frame(new_IFNy), title = 'ctr vs IFNy',
             annotate_by=top30.new_IFNy, ymax1 = 60, ymax2 = 61, xmax1 = -5, xmax2 = 10)


```

## Boxplot genes of interest

```{r dea.stim, echo=TRUE, fig.height = 4, fig.width = 5, fig.align = "center", message = FALSE, warning=FALSE, eval=TRUE}
for (i in unique(meta.CO$Line)){
  boxplot.g_ifny_byline <- boxplot.g_ifny[boxplot.g_ifny$Sample %in% rownames(meta.CO[!meta.CO$condition %in% 'LPS',][meta.CO[!meta.CO$condition %in% 'LPS',]$Line %in% i,]),]
  expression_data_long.ifny_byline <- gather(boxplot.g_ifny_byline, key = "Gene", value = "Expression", -Sample, -Stimulation)
  p <- ggplot(expression_data_long.ifny_byline,aes_string(x = 'Gene', y = 'Expression', fill = 'Stimulation')) +
    geom_boxplot(position = position_dodge(width = 0.8), width = 0.7)  +
    labs(y=paste('Expression in',i)) + 
    theme_minimal()
  plot(p)
}

```


## Top 40 DEGs heatmap

```{r heatmap.stim, echo=TRUE, fig.height = 4, fig.width = 10, fig.align = "center", message = FALSE, warning=FALSE, eval=TRUE}
ComplexHeatmap::Heatmap(hm_counts.ifny,
                        cluster_rows = T,
                        cluster_columns = T,
                        show_row_dend = T,
                        show_column_dend = T,
                        show_row_names = F,
                        show_column_names = F,
                        left_annotation = ra.ifny,
                        bottom_annotation = HeatmapAnnotation(
                          text = anno_text(colnames(hm_counts.ifny), rot = 300, just = "left",gp=gpar(fontsize=8))),
                        col = colorRampPalette(rev(RColorBrewer::brewer.pal(9,"RdBu")))(10),
                        name = "Z-score expression")

```

## Enrichment heatmap (gene sets of interest)
```{r heatmap.stim2, echo=TRUE, fig.height = 6, fig.width = 5, message = FALSE, warning=FALSE, eval=TRUE}

ComplexHeatmap::Heatmap(DEG.enrich_ifny,
                        cluster_rows = F,
                        cluster_columns = F,
                        show_row_dend = F,
                        show_column_dend = F,
                        show_row_names = T,
                        col = colorRampPalette(RColorBrewer::brewer.pal(9,"Blues"))(30),
                        name = "log2(q)",
)


```

## GO enrichment

```{r GO.stim, echo=TRUE, fig.height = 10, fig.width = 7, fig.align = "center", message = FALSE, warning=FALSE, eval=TRUE}
dotplot(new_IFNy.upregGO, split="ONTOLOGY", showCategory=10) + facet_grid(ONTOLOGY~., scale="free")
dotplot(new_IFNy.downregGO, split="ONTOLOGY", showCategory=10) + facet_grid(ONTOLOGY~., scale="free")

```

## iMG vs ocMG

```{r enrichment.stim, echo=TRUE, fig.height = 6, fig.width = 6, fig.align = "center", message = FALSE, warning=FALSE, eval=TRUE}
#==========iMG - COiMG correlation===============+#
#integrate iMG with COiMG
load('/Users/kubler01/Documents/R projects/bulk-org/data/Psamples_gene_matrix.RData')
genes_counts
meta_p <- data.frame(readxl::read_xlsx('/Users/kubler01/Documents/R projects/bulk-org/meta_P.xlsx'))
counts_p <- genes_counts[,colnames(genes_counts) %in% meta_p$ID]
counts_P.filt <- counts_p[rownames(counts_p) %in% counts_protcod2,]
rownames(counts_P.filt) <- make.unique(protcod_genes_reduced[,2])
#filter genes on expression
gene_names <- rownames(counts_P.filt)
cpm = edgeR::cpm(counts_P.filt)
median_genes_cpm <- enframe(rowMedians(as.matrix(counts_P.filt)), name = "Gene", value = "median_cpm")
median_genes_cpm <- cbind(median_genes_cpm, gene_names)
keep.exp <- dplyr::filter(median_genes_cpm, median_cpm > 1)
keep.exp <- keep.exp$gene_names

counts_P.filt2 <- counts_P.filt[keep.exp,]


dds.P <- DESeqDataSetFromMatrix(countData = round(counts_P.filt2),
                                   colData = meta_p,
                                   design = ~ RIN + `X260.280` + `X260.230` + type) # RIN + Line + Age + `260/230` + `260/280` + 

vsd.p <- vst(dds.P)
transformed.p <- data.frame(assay(vsd.p), check.names=F)


batch.p <- removeBatchEffect(transformed.p, 
                                covariates=as.matrix(cbind(
                                  meta_p$`X260.280`,
                                  meta_p$`X260.230`,
                                  meta_p$RIN)),
                                design=model.matrix(~ meta_p$type))


iMG <- batch.p[,colnames(batch.p) %in% meta_p[meta_p$type %in% 'iMG',]$ID]
ocMG <- batch.p[,colnames(batch.p) %in% meta_p[meta_p$type %in% 'ocMG',]$ID]
cor(iMG,ocMG)

df1 <- data.frame('iMG'=rowMeans(iMG))
df2 <- data.frame('ocMG'=rowMeans(ocMG))

df.plot <- cbind(df1,df2)

quantile(as.matrix(df1-df2))
rownames(df.plot)[df1-df2 >= 0.5 | df1-df2 <= -1]

Gene <- ifelse(rownames(df.plot) %in% rownames(df.plot)[df1-df2 >= 0.5 | df1-df2 <= -1], rownames(df.plot), "")

ggplot(df.plot, aes(x=iMG,y=ocMG))+
  geom_point() +
  labs(title = "Expression overlap iMG and ocMG",
       x = "Standardized iMG counts",
       y = "Standardized ocMG counts") +
  geom_smooth(method=lm,  linetype="dashed",
             color="darkred", fill="blue", se=TRUE) +
  geom_point(shape=18, color="grey")+
  stat_cor(method = "pearson", label.x = 0, label.y = 20)+
  geom_text_repel(data = df.plot, aes(x = iMG, y = ocMG, label = Gene), vjust = 3, size = 3) +
  theme_minimal()


```