---
title: "sc-org figures (AB)"
author: "Raphael Kubler"
date: "01/24/2024"
output:
  pdf_document:
    toc: yes
  rmarkdown::html_document:
    theme: united
    highlight: tango
    code_folding: hide
    toc: yes
    toc_float: yes
    df_print: paged
    smooth_scroll: yes
    number_sections: no
    self_contained: yes
  html_document:
    toc: yes
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(Seurat, lib.loc = "/usr/local/lib64/R/library")
library(Matrix, lib.loc = "/usr/local/lib64/R/library")
library(dplyr)
library(tidyverse)
library(ggplot2)

load("/sc/arion/projects/ad-omics/raphael/alice/sc-org/analysis/01142024_V2 analysis.RData")
```

# Single-cell RNA-seq analysis of COs vs COiMG

## UMAP

```{r umap, echo=TRUE, fig.height = 6, fig.width = 7, fig.align = "center", message = FALSE, warning=FALSE, eval=TRUE}
Idents(PV_filt) <- PV_filt$seurat_clusters
identity <- c('0'='Neuroepithelial Cells',
              '1'='Cortical neurons',
              '2'='Astrocyte-like Radial Glia',
              '3'='Radial Glia (UPR)',
              '4'='Mesenchymal/ChP (Cilia-associated)',
              '5'='Neuroepithelial/Radial Glia',
              '6'='Microglia',
              '7'='Microglia')
PV_filt <- RenameIdents(object = PV_filt, identity)
PV_filt@meta.data$identity <- Idents(PV_filt)
table(PV_filt$identity)


DimPlot(PV_filt, reduction = 'umap', group.by='identity')

```

```{r markers, echo=TRUE, fig.height = 6, fig.width = 12, fig.align = "center", message = FALSE, warning=FALSE, eval=TRUE}
SCpubr::do_DotPlot(PV_filt, features=list('Microglia'=AB_markers$Microglia,'Cilia'=AB_markers$Cilia,
                                          'ChP'=AB_markers$ChP),
                                          cluster.idents=F)+ 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))


```














